;;; 20220830 (C) Gunter Liszewski -*- mode: scheme; -*-
;;; our toying with Rubik's cube, and hacking away on the gnubik package

(define-module (gnu packages xen-0-gnubik)
  ;; #:use-module (ice-9 match)
  #:use-module ((guix licenses) #:prefix license:)
  ;; #:use-module (guix utils)
  #:use-module (guix packages)
  #:use-module (guix download)
  ;; #:use-module (guix git-download)
  ;; #:use-module (guix svn-download)
  ;; #:use-module (guix gexp)
  #:use-module (gnu packages)
  ;; #:use-module (gnu packages adns)
  ;; #:use-module (gnu packages algebra)
  #:use-module (gnu packages autotools)
  ;; #:use-module (gnu packages backup)
  ;; #:use-module (gnu packages base)
  ;; #:use-module (gnu packages build-tools)
  ;; #:use-module (gnu packages admin)
  ;; #:use-module (gnu packages audio)
  ;; #:use-module (gnu packages avahi)
  ;; #:use-module (gnu packages assembly)
  ;; #:use-module (gnu packages bash)
  ;; #:use-module (gnu packages bison)
  ;; #:use-module (gnu packages boost)
  ;; #:use-module (gnu packages check)
  ;; #:use-module (gnu packages cmake)
  ;; #:use-module (gnu packages compression)
  ;; #:use-module (gnu packages code)
  ;; #:use-module (gnu packages cpp)
  ;; #:use-module (gnu packages curl)
  ;; #:use-module (gnu packages crypto)
  ;; #:use-module (gnu packages cyrus-sasl)
  ;; #:use-module (gnu packages documentation)
  ;; #:use-module (gnu packages docbook)
  ;; #:use-module (gnu packages emulators)
  ;; #:use-module (gnu packages flex)
  ;; #:use-module (gnu packages fltk)
  ;; #:use-module (gnu packages fonts)
  ;; #:use-module (gnu packages fontutils)
  ;; #:use-module (gnu packages freedesktop)
  ;; #:use-module (gnu packages fribidi)
  ;; #:use-module (gnu packages game-development)
  ;; #:use-module (gnu packages gcc)
  #:use-module (gnu packages gettext)
  ;; #:use-module (gnu packages ghostscript)
  ;; #:use-module (gnu packages gimp)
  #:use-module (gnu packages gl)
  ;; #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  ;; #:use-module (gnu packages gnu-doc)
  ;; #:use-module (gnu packages gnupg)
  ;; #:use-module (gnu packages gnuzilla)
  ;; #:use-module (gnu packages golang)
  ;; #:use-module (gnu packages gperf)
  ;; #:use-module (gnu packages graphics)
  ;; #:use-module (gnu packages graphviz)
  ;; #:use-module (gnu packages gsasl)
  ;; #:use-module (gnu packages gstreamer)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages guile)
  ;; #:use-module (gnu packages haskell)
  ;; #:use-module (gnu packages haskell-crypto)
  ;; #:use-module (gnu packages haskell-xyz)
  ;; #:use-module (gnu packages icu4c)
  ;; #:use-module (gnu packages image)
  ;; #:use-module (gnu packages imagemagick)
  ;; #:use-module (gnu packages javascript)
  ;; #:use-module (gnu packages kde)
  ;; #:use-module (gnu packages kde-frameworks)
  ;; #:use-module (gnu packages less)
  ;; #:use-module (gnu packages lesstif)
  ;; #:use-module (gnu packages libcanberra)
  ;; #:use-module (gnu packages libedit)
  ;; #:use-module (gnu packages libidn)
  ;; #:use-module (gnu packages libunwind)
  ;; #:use-module (gnu packages linux)
  ;; #:use-module (gnu packages llvm)
  ;; #:use-module (gnu packages lua)
  ;; #:use-module (gnu packages man)
  ;; #:use-module (gnu packages maths)
  ;; #:use-module (gnu packages messaging)
  ;; #:use-module (gnu packages mp3)
  ;; #:use-module (gnu packages music)
  ;; #:use-module (gnu packages multiprecision)
  ;; #:use-module (gnu packages ncurses)
  ;; #:use-module (gnu packages netpbm)
  ;; #:use-module (gnu packages networking)
  ;; #:use-module (gnu packages ocaml)
  ;; #:use-module (gnu packages opencl)
  ;; #:use-module (gnu packages pcre)
  ;; #:use-module (gnu packages perl)
  ;; #:use-module (gnu packages perl-check)
  ;; #:use-module (gnu packages perl-compression)
  #:use-module (gnu packages pkg-config)
  ;; #:use-module (gnu packages pretty-print)
  ;; #:use-module (gnu packages protobuf)
  ;; #:use-module (gnu packages pulseaudio)
  ;; #:use-module (gnu packages python)
  ;; #:use-module (gnu packages python-web)
  ;; #:use-module (gnu packages python-xyz)
  ;; #:use-module (gnu packages qt)
  ;; #:use-module (gnu packages readline)
  ;; #:use-module (gnu packages ruby)
  ;; #:use-module (gnu packages shells)
  ;; #:use-module (gnu packages sdl)
  ;; #:use-module (gnu packages serialization)
  ;; #:use-module (gnu packages sqlite)
  ;; #:use-module (gnu packages squirrel)
  ;; #:use-module (gnu packages swig)
  ;; #:use-module (gnu packages tcl)
  ;; #:use-module (gnu packages terminals)
  ;; #:use-module (gnu packages texinfo)
  ;; #:use-module (gnu packages textutils)
  ;; #:use-module (gnu packages tls)
  ;; #:use-module (gnu packages unicode)
  ;; #:use-module (gnu packages upnp)
  ;; #:use-module (gnu packages video)
  ;; #:use-module (gnu packages vulkan)
  ;; #:use-module (gnu packages web)
  ;; #:use-module (gnu packages wget)
  ;; #:use-module (gnu packages wxwidgets)
  ;; #:use-module (gnu packages xdisorg)
  #:use-module (gnu packages xorg)
  ;; #:use-module (gnu packages xiph)
  ;; #:use-module (gnu packages xml)
  ;; #:use-module (guix build-system copy)
  ;; #:use-module (guix build-system cmake)
  ;; #:use-module (guix build-system glib-or-gtk)
  #:use-module (guix build-system gnu)
  ;; #:use-module (guix build-system go)
  ;; #:use-module (guix build-system meson)
  ;; #:use-module (guix build-system perl)
  ;; #:use-module (guix build-system python)
  ;; #:use-module (guix build-system qt)
  ;; #:use-module (guix build-system scons)
  ;; #:use-module (guix build-system trivial)
  ;; #:use-module ((srfi srfi-1) #:hide (zip))
  ;; #:use-module (srfi srfi-26))
  )

(define-public gnubik-here
  (package
    (name "gnubik-here")
    (version "2.4.3")
    (source
     (origin
      (method url-fetch)
      (uri (string-append "mirror://gnu/gnubik/gnubik-"
                          version ".tar.gz"))
      (sha256
       (base32
        "1vlf924mq8hg93bsjj0rzvs0crc6psmlxyc6zn0fr7msnmpx6gib"))))
    (build-system gnu-build-system)
    (arguments
     '(#:phases (modify-phases %standard-phases
                  (add-after 'unpack 'skip-gtk-update-icon-cache
                    (lambda _
                      ;; Do not attempt to run 'gtk-update-icon-cache', which is
                      ;; unnecessary and causes a needless dependency on glib.
                      (substitute* "Makefile.in"
                        (("gtk-update-icon-cache")
                         "true"))
                      (substitute* "configure"
                        (("guile-2.0")
                         "guile-3.0"))
                      #t)))))
    (inputs (list gtk+-2
                  mesa
                  glu
                  libx11
                  guile-3.0-latest
                  gtkglext))
    (native-inputs (list autoconf
                         automake
                         gettext-minimal
                         pkg-config))
    (home-page "https://www.gnu.org/software/gnubik/")
    (synopsis "3d Rubik's cube game, its Guix gnubik package un-hacked")
    (description
     "GNUbik is a puzzle game in which you must manipulate a cube to make
each of its faces have a uniform color.  The game is customizable, allowing
you to set the size of the cube (the default is 3x3) or to change the colors.
You may even apply photos to the faces instead of colors.  The game is
scriptable with Guile.")
    (license license:gpl3+)))
